plugins:
  - rubocop-ordered_methods
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/FileName:
  Exclude:
    - ../lib/rubocop-hanami.rb

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/SpecFilePathFormat:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
