[task_config]
includes = ["scripts"]

[tasks.format]
alias = ["fmt"]
description = "Format all files"
depends = ["format:**"]

[tasks.lint]
alias = ["l"]
description = "Lint all files"
depends = ["lint:**"]

[tools]
editorconfig-checker = "3.11"
markdownlint-cli2 = "0.23"
ruby = "4"
shellcheck = "0.11"
shfmt = "3.14"
yamlfmt = "0.21"
